mods_soil <- list(
    "Hab"=list(
        .~. + soilc,
        .~. + soilc + pAspen,
        .~. + soilc + pWater_KM,
        .~. + soilc + pWet_KM,
        .~. + soilc + pWetWater_KM,
        .~. + soilc + pAspen + pWater_KM,
        .~. + soilc + pAspen + pWet_KM,
        .~. + soilc + pAspen + pWetWater_KM),
    "Contrast"=list(
        .~. + ROAD,
        .~. + ROAD + mWell,
        .~. + ROAD + mWell + mSoft),
    "ARU"=list(
        .~. + CMETHOD),
    "Space"=list(
        .~.+ xPET,## climate only
        .~.+ xMAT,
        .~.+ xAHM,
        .~.+ xFFP,
        .~.+ xMAP + xFFP,
        .~.+ xMAP + xFFP + xMAP:xFFP,
        .~.+ xMAT + xMAP + xPET + xAHM,
        .~.+ xMAT + xMAP + xPET + xAHM + xPET:xMAP + xMAT:xAHM,
        .~.+ xMAT + xMAP,
        .~.+ xMWMT + xMCMT,
        .~.+ xAHM + xPET,
        .~.+ xlat + xlong + xlat:xlong + xPET,## linear lat-long and climate
        .~.+ xlat + xlong + xlat:xlong + xMAT,
        .~.+ xlat + xlong + xlat:xlong + xAHM,
        .~.+ xlat + xlong + xlat:xlong + xFFP,
        .~.+ xlat + xlong + xlat:xlong + xMAP + xFFP,
        .~.+ xlat + xlong + xlat:xlong + xMAP + xFFP + xMAP:xFFP,
        .~.+ xlat + xlong + xlat:xlong + xMAT + xMAP + xPET + xAHM,
        .~.+ xlat + xlong + xlat:xlong + xMAT + xMAP + xPET + xAHM + xPET:xMAP + xMAT:xAHM,
        .~.+ xlat + xlong + xlat:xlong + xMAT + xMAP,
        .~.+ xlat + xlong + xlat:xlong + xMWMT + xMCMT,
        .~.+ xlat + xlong + xlat:xlong + xAHM + xPET,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xPET,## quadratic lat-long and climate
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAT,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xAHM,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xFFP,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAP + xFFP,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAP + xFFP + xMAP:xFFP,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAT + xMAP + xPET + xAHM,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAT + xMAP + xPET + xAHM + xPET:xMAP + xMAT:xAHM,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMAT + xMAP,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xMWMT + xMCMT,
        .~.+ xlat + xlong + xlat:xlong + xlat2 + xlong2 + xAHM + xPET),
    "HF"=list(
        .~.+ THF_KM,
        .~.+ Lin_KM + Nonlin_KM,
        .~.+ Succ_KM + Alien_KM,
        .~.+ Succ_KM + Noncult_KM + Cult_KM,
        .~.+ THF_KM + THF2_KM,
        .~.+ Lin_KM + Nonlin_KM + Nonlin2_KM,
        .~.+ Succ_KM + Alien_KM + Succ2_KM,
        .~.+ Succ_KM + Noncult_KM + Cult_KM + Succ2_KM,
        .~.+ Succ_KM + Alien_KM + Alien2_KM,
        .~.+ Succ_KM + Noncult_KM + Cult_KM + Noncult2_KM,
        .~.+ Succ_KM + Alien_KM + Succ2_KM + Alien2_KM,
        .~.+ Succ_KM + Noncult_KM + Cult_KM + Succ2_KM + Noncult2_KM),
    "Year"=list( # 8
        .~.+ YR))
