---
title: ARU related modeling considerations for CONI recognizer data
author: P. Solymos
date: 2016-04-08
output: 
  pdf_document:
    toc: false
    toc_depth: 2
---

# Data and model

$Y_{ij}$ is number of call events at location $i$ ($i=1,...,n$) and 
time $j$ ($j=1,...,m$), and of a recording session duration $t_{ij}$
(usually 3 or 10 minutes).

Location (habitat, clinate), time (Julian day, time), 
recording session (location and time) 
specific predictor variables might be considered in modeling.

Expected value of $Y_{ij}$ may be written as 
$E[Y_{ij}] = N_{ij} \lambda_{ij} t_{ij}$,
where $N_{ij}$ is the abundance of the species within effective detection area (EDA)
around the ARU , 
$\lambda_{ij}$ is the call rate per unit time (1 min) given use.
$N$  is either 0 when the EDA is not used or assumed to be 1 when EDA is used.
The $max(N) \leq 1$ constraint can be assured by reducing EDA sufficiently.

The recording session that contain at least one detection can be used to
estimate call rate ($\hat{\lambda}_{ij}$) 
based on time-to-event data with time specific
predictors in a survival modeling (or possibly time-removal sampling) 
framework.

The distribution of $Y$ is a zero-inflated count distribution where
$N$ is the zero-inflation related random state that is of interest.
The joint likelihood for a Bernoulli-Poisson mixture can be written as:

$$P(Y_{ij}=y_{ij}) = I(y_{ij}=0) (1-\gamma_{ij}) + \gamma_{ij} e^{-\lambda_{ij} t_{ij}} \frac{\lambda_{ij} t_{ij}^{y}}{y!} $$

# Parameter estimation

$W_{ij}$ is a binary random variable ($W_{ij} = I(Y_{ij}>0)$):

$$ P(W_{ij}=0) = (1-\gamma_{ij}) + \gamma_{ij} e^{-\lambda_{ij} t_{ij}} $$
$$ P(W_{ij}=1) = \gamma_{ij} (1 - e^{-\lambda_{ij} t_{ij}}) $$

```{r}
method="Nelder-Mead"
inits, control=list()
hessian=FALSE
good.num.limit <- c(.Machine$double.xmin, .Machine$double.xmax)^(1/3)
linkinvz <- binomial(linkz)$linkinv
## d0 is simply calculated as exp(-lambda*t)
nll_Np <- function(parms, d0) {
    gamma <- as.vector(linkinvz(Z %*% parms))
    loglik <- sum(weights * ifelse(Y==0, log((1-gamma) + gamma * d0)), log(gamma * (1 - d0))))
    if (!is.finite(loglik) || is.na(loglik))
        loglik <- -good.num.limit[2]
    -loglik
}
res_PL <- suppressWarnings(optim(inits[(np-kz+1):np], nll_PL, 
    logd0=logd0,
    method=method, hessian=hessian, control=control, ...))
res_PL$coef <- res_PL$par
res_PL$loglik <- -res_PL$value
res_PL$vcov <- NULL
res_PL$vcov <- solve(res_PL$hessian)
res_PL$par <- res_PL$value <- NULL

    
```
