---
title: "Converting revisit/prior totals to yearly rate"
author: "D. Huggard "
output: pdf_document
---

Using the mean time-between-visits weighted by the initial abundance
to convert `sum(prior_visit) / sum(revisit)` into a yearly rate is exactly
correct when the rate is 1 (no trend), and is very close over a
reasonable range of rates.
It is only off when the rate of change is very high, increasing or decreasing.

## Calculations

* Initial value for each site is `X0[i]`,
* time between visits for each site is `T[i]`,
* yearly rate of change is `lambda`,
* therefore, the revisit value is `XR[i] = X0[i]*(lambda^T[i])`.
* The weighted mean is `WM = sum(T[i]*X0[i])/sum(X0[i])`.
* We calculate total change `TC = sum(XR[i])/sum(X0[i])`.

`TC^(1/WM) = lambda` when `lambda = 1`, and is very close over ranges of
`lambda` values from 0.8 to 1.25 (if the range of `T[i]`'s isn't excessive,
e.g., from 3--8 years like we have in our revisits).

The distribution of revisit times have an effect as well.

```{r}
f <- function(lambda=1) {
    XR <- X0*(lambda^T)
    WM <- sum(T*X0)/sum(X0)
    TC <- sum(XR)/sum(X0)
    TC^(1/WM)
}
N <- 1000
set.seed(1)
T <- sample(1:5, N, replace=TRUE)
X0 <- runif(N, 0, 1)
lambda <- seq(0.1, 2, by=0.01)
values1 <- sapply(lambda, f)
T <- T + 5
values2 <- sapply(lambda, f)
T <- T + 5
values3 <- sapply(lambda, f)
plot(lambda, values1, xlab="Yearly rate of change",
    ylab="Approximation", type="l", col=1, lwd=2)
lines(lambda, values2, col=2, lwd=2)
lines(lambda, values3, col=4, lwd=2)
abline(0, 1, lty=2, col="grey")
legend("topleft", bty="n", lwd=2, col=c(1, 2, 4), 
    legend=c("T in 1-5 yrs", "T in 6-10 yrs", "T in 11-15 yrs"))
```

